package com.hotel.automation.controller;

import java.util.Observer;

/**
 * Interface that needs to be implemented by controllers for sensor data
 * It is also a listener for events generated by a sensor hub
 * @author avinash
 *
 */
public interface DataController extends Observer {
	/**
	 * Placeholder method for ingesting sensor data
	 */
	public void ingestData();
}
